# Constants for browser located in this file.

# CONFIG DIRECTORY NAMES
DIRECTORY_CONFIGURATIONS = 'configurations'
DIRECTORY_TOPICS = 'topics'
DIRECTORY_AVRO_SCHEMAS = 'avro_schemas'
DIRECTORY_DEPLOYMENT_SCRIPTS = 'deployment_scripts'

# CONFIG FILENAMES
FILE_MAIN_CONFIG = 'main_config.yml'
FILE_LOGGER_CONFIG = 'logger_config.yml'
FILE_AVRO_TOPICS = 'avro_topics.yml'
FILE_UI = 'splash.html'

# INCOMING REQUEST PARAMS
REQUEST_SEARCH_STRING_KEY = 'searchParam'
REQUEST_ENVIRONMENT_KEY = 'environment'
REQUEST_INCLUDE_KAFKA_METADATA_KEY = 'includeKafkaMetadata'
REQUEST_INCLUDE_DELIMITER_KEY = 'includeDelimiter'
REQUEST_OTHER_TOPIC_KEY = 'otherTopic'
REQUEST_JSON_TOPICS_KEY = 'json_topics'
REQUEST_AVRO_TOPICS_KEY = 'avro_topics'
REQUEST_NOT_BEFORE_KEY = 'notBefore'
REQUEST_SEARCH_COUNT_KEY = 'search_count'
REQUEST_UI_FORM_JSON_TOPICS_KEY = 'json_topics[]'
REQUEST_UI_FORM_AVRO_TOPICS_KEY = 'avro_topics[]'

# REQUEST_PARAMS
PARAM_SEARCH_STRING_KEY = 'search_string'
PARAM_ENVIRONMENT_KEY = 'environment'
PARAM_INCLUDE_KAFKA_METADATA_KEY = 'include_kafka_metadata'
PARAM_INCLUDE_DELIMITER_KEY = 'delimiter'
PARAM_OTHER_TOPIC_KEY = 'other_topic'
PARAM_JSON_TOPICS_KEY = 'json_topics'
PARAM_AVRO_TOPICS_KEY = 'avro_topics'
PARAM_NOT_BEFORE_KEY = 'not_before'
PARAM_SEARCH_COUNT_KEY = 'search_count'

# RESPONSE KEYS
RESPONSE_JSON_TOPICS_PREFIX = 'JSON_TOPIC_'
RESPONSE_AVRO_TOPICS_PREFIX = 'AVRO_TOPIC_'
RESPONSE_ERROR_KEY = 'ERROR'

# LOGGER
LOGGER_NAME = "browser_request_logger"
LOGGER_DISABLE_KEY = 'logger.enable'
LOGGER_PATH_KEY = 'logger.requests.path'
